#ifndef COMMAND_H
#define COMMAND_H

#include "controller_reader.h"

// These must match the values in shared/controller.fbs
// we use the definitions generated by flatcc
#define MODE_IDLE Willa_DriveController_MotorMode_Idle
#define MODE_BRAKE Willa_DriveController_MotorMode_Brake
#define MODE_FORWARD Willa_DriveController_MotorMode_Forward
#define MODE_REVERSE Willa_DriveController_MotorMode_Reverse

struct CarCommand
{
    short steer;
    Willa_DriveController_MotorMode_enum_t motor_mode;
    unsigned short motor_power;
    unsigned short front_lights;
    unsigned short rear_lights;
    unsigned short horn;
};

extern CarCommand command;
extern CarCommand idle_command;

#endif // COMMAND_H