#ifndef CONTROLLER_VERIFIER_H
#define CONTROLLER_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef CONTROLLER_READER_H
#include "controller_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int Willa_DriveController_DriveControl_verify_table(flatcc_table_verifier_descriptor_t *td);

static int Willa_DriveController_DriveControl_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* steer */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* motor_mode */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* motor_power */)) return ret;
    return flatcc_verify_ok;
}

static inline int Willa_DriveController_DriveControl_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Willa_DriveController_DriveControl_identifier, &Willa_DriveController_DriveControl_verify_table);
}

static inline int Willa_DriveController_DriveControl_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Willa_DriveController_DriveControl_type_identifier, &Willa_DriveController_DriveControl_verify_table);
}

static inline int Willa_DriveController_DriveControl_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &Willa_DriveController_DriveControl_verify_table);
}

static inline int Willa_DriveController_DriveControl_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &Willa_DriveController_DriveControl_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* CONTROLLER_VERIFIER_H */
