#ifndef CONTROLLER_READER_H
#define CONTROLLER_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct Willa_DriveController_DriveControl_table *Willa_DriveController_DriveControl_table_t;
typedef struct Willa_DriveController_DriveControl_table *Willa_DriveController_DriveControl_mutable_table_t;
typedef const flatbuffers_uoffset_t *Willa_DriveController_DriveControl_vec_t;
typedef flatbuffers_uoffset_t *Willa_DriveController_DriveControl_mutable_vec_t;
#ifndef Willa_DriveController_DriveControl_file_identifier
#define Willa_DriveController_DriveControl_file_identifier 0
#endif
/* deprecated, use Willa_DriveController_DriveControl_file_identifier */
#ifndef Willa_DriveController_DriveControl_identifier
#define Willa_DriveController_DriveControl_identifier 0
#endif
#define Willa_DriveController_DriveControl_type_hash ((flatbuffers_thash_t)0xfb86a9e9)
#define Willa_DriveController_DriveControl_type_identifier "\xe9\xa9\x86\xfb"
#ifndef Willa_DriveController_DriveControl_file_extension
#define Willa_DriveController_DriveControl_file_extension "bin"
#endif

typedef int8_t Willa_DriveController_MotorMode_enum_t;
__flatbuffers_define_integer_type(Willa_DriveController_MotorMode, Willa_DriveController_MotorMode_enum_t, 8)
#define Willa_DriveController_MotorMode_Idle ((Willa_DriveController_MotorMode_enum_t)INT8_C(0))
#define Willa_DriveController_MotorMode_Brake ((Willa_DriveController_MotorMode_enum_t)INT8_C(1))
#define Willa_DriveController_MotorMode_Forward ((Willa_DriveController_MotorMode_enum_t)INT8_C(2))
#define Willa_DriveController_MotorMode_Reverse ((Willa_DriveController_MotorMode_enum_t)INT8_C(3))

static inline const char *Willa_DriveController_MotorMode_name(Willa_DriveController_MotorMode_enum_t value)
{
    switch (value) {
    case Willa_DriveController_MotorMode_Idle: return "Idle";
    case Willa_DriveController_MotorMode_Brake: return "Brake";
    case Willa_DriveController_MotorMode_Forward: return "Forward";
    case Willa_DriveController_MotorMode_Reverse: return "Reverse";
    default: return "";
    }
}

static inline int Willa_DriveController_MotorMode_is_known_value(Willa_DriveController_MotorMode_enum_t value)
{
    switch (value) {
    case Willa_DriveController_MotorMode_Idle: return 1;
    case Willa_DriveController_MotorMode_Brake: return 1;
    case Willa_DriveController_MotorMode_Forward: return 1;
    case Willa_DriveController_MotorMode_Reverse: return 1;
    default: return 0;
    }
}



struct Willa_DriveController_DriveControl_table { uint8_t unused__; };

static inline size_t Willa_DriveController_DriveControl_vec_len(Willa_DriveController_DriveControl_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Willa_DriveController_DriveControl_table_t Willa_DriveController_DriveControl_vec_at(Willa_DriveController_DriveControl_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Willa_DriveController_DriveControl_table_t, vec, i, 0)
__flatbuffers_table_as_root(Willa_DriveController_DriveControl)

__flatbuffers_define_scalar_field(0, Willa_DriveController_DriveControl, steer, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(1, Willa_DriveController_DriveControl, motor_mode, Willa_DriveController_MotorMode, Willa_DriveController_MotorMode_enum_t, INT8_C(0))
__flatbuffers_define_scalar_field(2, Willa_DriveController_DriveControl, motor_power, flatbuffers_float, float, 0.00000000f)


#include "flatcc/flatcc_epilogue.h"
#endif /* CONTROLLER_READER_H */
