#ifndef CONTROLLER_BUILDER_H
#define CONTROLLER_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef CONTROLLER_READER_H
#include "controller_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __Willa_DriveController_MotorMode_formal_args , Willa_DriveController_MotorMode_enum_t v0
#define __Willa_DriveController_MotorMode_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, Willa_DriveController_MotorMode, Willa_DriveController_MotorMode_enum_t)

static const flatbuffers_voffset_t __Willa_DriveController_DriveControl_required[] = { 0 };
typedef flatbuffers_ref_t Willa_DriveController_DriveControl_ref_t;
static Willa_DriveController_DriveControl_ref_t Willa_DriveController_DriveControl_clone(flatbuffers_builder_t *B, Willa_DriveController_DriveControl_table_t t);
__flatbuffers_build_table(flatbuffers_, Willa_DriveController_DriveControl, 3)

#define __Willa_DriveController_DriveControl_formal_args , float v0, Willa_DriveController_MotorMode_enum_t v1, float v2
#define __Willa_DriveController_DriveControl_call_args , v0, v1, v2
static inline Willa_DriveController_DriveControl_ref_t Willa_DriveController_DriveControl_create(flatbuffers_builder_t *B __Willa_DriveController_DriveControl_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, Willa_DriveController_DriveControl, Willa_DriveController_DriveControl_file_identifier, Willa_DriveController_DriveControl_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, Willa_DriveController_DriveControl_steer, flatbuffers_float, float, 4, 4, 0.00000000f, Willa_DriveController_DriveControl)
__flatbuffers_build_scalar_field(1, flatbuffers_, Willa_DriveController_DriveControl_motor_mode, Willa_DriveController_MotorMode, Willa_DriveController_MotorMode_enum_t, 1, 1, INT8_C(0), Willa_DriveController_DriveControl)
__flatbuffers_build_scalar_field(2, flatbuffers_, Willa_DriveController_DriveControl_motor_power, flatbuffers_float, float, 4, 4, 0.00000000f, Willa_DriveController_DriveControl)

static inline Willa_DriveController_DriveControl_ref_t Willa_DriveController_DriveControl_create(flatbuffers_builder_t *B __Willa_DriveController_DriveControl_formal_args)
{
    if (Willa_DriveController_DriveControl_start(B)
        || Willa_DriveController_DriveControl_steer_add(B, v0)
        || Willa_DriveController_DriveControl_motor_power_add(B, v2)
        || Willa_DriveController_DriveControl_motor_mode_add(B, v1)) {
        return 0;
    }
    return Willa_DriveController_DriveControl_end(B);
}

static Willa_DriveController_DriveControl_ref_t Willa_DriveController_DriveControl_clone(flatbuffers_builder_t *B, Willa_DriveController_DriveControl_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (Willa_DriveController_DriveControl_start(B)
        || Willa_DriveController_DriveControl_steer_pick(B, t)
        || Willa_DriveController_DriveControl_motor_power_pick(B, t)
        || Willa_DriveController_DriveControl_motor_mode_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, Willa_DriveController_DriveControl_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* CONTROLLER_BUILDER_H */
